### ISSUE TITLE
Missing library license

### ISSUE THREAD

**Issue by maurits150** [AlexSwift/SantosRP#1]
https://github.com/AlexSwift/SantosRP/blob/f7360bdafd6d0cc4cd18ff817f3bcb4e2d25f8fb/gearfox/gamemode/shared/libs/simploo.lua

https://github.com/maurits150/simploo/blob/1.0/simploo.lua

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Thanks for using simploo!

**Comment by AlexSwift** [comment]
Hi Maurits. Added that back in. Really sorry about it being deleted, not sure when that happened, or why. It's back now. Thanks for letting me know :)
