### ISSUE TITLE
forgot mysql.lua?

### ISSUE THREAD

**Issue by formatme** [AlexSwift/SantosRP#2]
mysql.New doesnt work etc

**Comment by WilliamCTurner** [comment]
I have gotton the same problem

**Comment by kevzilahd** [comment]
Yeah same problem, even adding the gm_mysql module doesn't even load, and it's asking for the mysql.lua module/file which we don't know what exists in that file and adding a mysql.lua file using their test one modified doesn't work as it doesn't find the module so mysql.lua doesn't load correctly.

Must be a way to get around it as others have just being dumb.

**Comment by AlexSwift** [comment]
https://github.com/alexgrist/GLua-MySQL-Wrapper/blob/master/mysql.lua
