### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by a-ja** [AlexSwift/SantosRP#3]
Its says "Not a Tester" could someone plz help with this??

**Comment by AlexSwift** [comment]
https://github.com/AlexSwift/SantosRP/blob/master/santosrp/gamemode/server/mysql/mysql_betatester.lua

There is a table in your database pertaining to who is a "beta tester". Add you SteamID64 into that table and you're good to go. Alternatively, disable beta only:

https://github.com/AlexSwift/SantosRP/blob/master/santosrp/gamemode/shared.lua#L4
Change to false.

**Comment by a-ja** [comment]
Sorry that i am maybe asking to much :) but (Yes there always a but)
What does this mean?

[ERROR] gamemodes/gearfox/gamemode/shared/libs/simploo.lua:358: class LuaClass: santosRP.Flags <class> {0x39333ef0}: invalid read access attempt to protected member 'CreateClass': accessed by - code outside class boundaries -
  1. error - [C]:-1
   2. __index - gamemodes/gearfox/gamemode/shared/libs/simploo.lua:358
    3. v - gamemodes/santosrp/gamemode/shared/skills.lua:12
     4. unknown - lua/includes/modules/hook.lua:84

**Comment by AlexSwift** [comment]
I've updated shared/flags.lua to fix the problem you've been having. I do not offer help running this gamemode, and I'm afraid any future issues you may have with the gamemode you'll have to fix yourself. This was still WIP when I was working on it, so there are still some things that may not work.
